// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestQuiz.DataContext;

namespace TestQuiz.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("DataLayes.Models.Answer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.HasKey("id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("DataLayes.Models.Response", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Answerid");

                    b.Property<string>("Content");

                    b.HasKey("id");

                    b.HasIndex("Answerid");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("DataLayes.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Passwod");

                    b.Property<string>("Role");

                    b.Property<string>("Surname");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataLayes.Models.Response", b =>
                {
                    b.HasOne("DataLayes.Models.Answer", "Answer")
                        .WithMany("Responses")
                        .HasForeignKey("Answerid");
                });
#pragma warning restore 612, 618
        }
    }
}
